import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { Marked, type Tokens } from 'marked';

export interface DocEntry {
  /** The heading this page sits under in the contents. Groups appear in first-mention order. */
  group: string;
  /** The URL segment and the filename, without `.md`. Keeping them one value is the drift guard. */
  slug: string;
  title: string;
  summary: string;
}

export interface DocGroup {
  group: string;
  entries: DocEntry[];
}

export interface DocHeading {
  depth: number;
  text: string;
  id: string;
}

export interface DocPage {
  entry: DocEntry;
  html: string;
  /** Sections the reader can be sent to — `##` and below. The page's own `#` is its title. */
  headings: DocHeading[];
}

/** One row of the table the API writes; see `apps/api/src/docs/endpoint-reference.ts`. */
export interface EndpointDoc {
  method: string;
  path: string;
  statusCode: number;
  access: { kind: 'public' | 'optional-session' | 'session'; roles: string[] };
  controller: string;
  handler: string;
}

export interface EndpointsFile {
  generatedBy: string;
  endpoints: EndpointDoc[];
}

const CONTENT_DIR = resolve(process.cwd(), 'content');

/**
 * The manifest is read rather than imported so that a page can be added by writing a file and a
 * line here, with no third place to remember.
 */
const ENTRIES = JSON.parse(readFileSync(resolve(CONTENT_DIR, 'docs.json'), 'utf8')) as DocEntry[];

/**
 * The route table, generated by the API package and committed as a file. Read once at module load
 * so that a missing or corrupt export stops the build rather than printing a page whose table is
 * quietly shorter than the API.
 */
const ENDPOINTS = JSON.parse(
  readFileSync(resolve(CONTENT_DIR, 'endpoints.json'), 'utf8'),
) as EndpointsFile;

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

/**
 * Ids have to be stable across builds and unique within a page. A reader sent to `#the-api` should
 * land on the section they were promised even after a second heading with the same words is added
 * above it, so the collision is resolved by position rather than by a hash of the content.
 */
function uniqueId(base: string, seen: Set<string>): string {
  const root = base || 'section';
  let id = root;
  let taken = 2;

  while (seen.has(id)) {
    id = `${root}-${taken}`;
    taken += 1;
  }
  seen.add(id);
  return id;
}

type HeadingWithId = Tokens.Heading & { id?: string };

const marked = new Marked({ gfm: true });

marked.use({
  renderer: {
    heading(token) {
      const heading = token as HeadingWithId;
      const id = heading.id ?? slugify(heading.text);
      return `<h${heading.depth} id="${id}">${marked.parseInline(heading.text, { async: false })}</h${heading.depth}>`;
    },
  },
});

export function docSlugs(): string[] {
  return ENTRIES.map((entry) => entry.slug);
}

/**
 * Every path the export emits for the docs, and the only list an internal link on this site is
 * allowed to point at. The index is deliberately given the short path rather than also appearing
 * as `/docs/index`: two URLs for one page is two things that can drift, and one of them would be
 * a link nobody wrote on purpose.
 */
export function docRoutes(): string[] {
  return [
    '/docs',
    ...ENTRIES.filter((entry) => entry.slug !== 'index').map((entry) => `/docs/${entry.slug}`),
  ];
}

export function docGroups(): DocGroup[] {
  const order: string[] = [];
  const byGroup = new Map<string, DocEntry[]>();

  for (const entry of ENTRIES) {
    const existing = byGroup.get(entry.group);
    if (existing) {
      existing.push(entry);
    } else {
      byGroup.set(entry.group, [entry]);
      order.push(entry.group);
    }
  }

  return order.map((group) => ({ group, entries: byGroup.get(group) as DocEntry[] }));
}

/**
 * The one sentence a reader needs beside a path: not the decorator's word for it but who, in
 * practice, gets past the guard.
 */
function accessLabel(access: EndpointDoc['access']): string {
  if (access.kind === 'public') return 'anyone';
  if (access.kind === 'optional-session') return 'anyone, session read if offered';

  return access.roles.length > 0 ? access.roles.join(' or ') : 'any signed-in account';
}

function resourceOf(path: string): string {
  // `/api/v1/<resource>/…` — the segment a reader is scanning for once they know the URL.
  return path.split('/')[3] ?? '';
}

/**
 * One table per resource, because sixty routes in a single block is a page nobody can hold still
 * long enough to search. The groups come out in the order the export sorted them, which is by path,
 * so a reader who knows the URL does not have to know the module layout to find it.
 */
function endpointTables(): string {
  const groups: { resource: string; rows: EndpointDoc[] }[] = [];

  for (const endpoint of ENDPOINTS.endpoints) {
    const resource = resourceOf(endpoint.path);
    const last = groups[groups.length - 1];

    if (last?.resource === resource) last.rows.push(endpoint);
    else groups.push({ resource, rows: [endpoint] });
  }

  return groups
    .map((group) =>
      [
        `### ${group.resource}`,
        '',
        '| Method | Path | Who may call | Answers |',
        '| --- | --- | --- | --- |',
        ...group.rows.map(
          (row) =>
            `| \`${row.method}\` | \`${row.path}\` | ${accessLabel(row.access)} | ${row.statusCode} |`,
        ),
      ].join('\n'),
    )
    .join('\n\n');
}

/** The fence a page writes to ask for the generated table. */
const ENDPOINT_MARKER = /^```endpoints\n```$/m;

/**
 * A fence rather than a template tag, so the marker survives as something a markdown reader can
 * see: an unfilled ```endpoints block prints its own name on the page, which is the failure the
 * "no marker unfilled" test is watching for.
 */
function fillGenerated(markdown: string): string {
  return markdown.replace(ENDPOINT_MARKER, endpointTables());
}

export function readDoc(slug: string): DocPage {
  const entry = ENTRIES.find((candidate) => candidate.slug === slug);

  if (!entry) {
    throw new Error(`No docs page "${slug}": content/docs.json does not list it`);
  }

  const path = resolve(CONTENT_DIR, `${slug}.md`);
  if (!existsSync(path)) {
    throw new Error(
      `content/docs.json lists "${slug}" but content/${slug}.md is not there — the manifest and the folder have drifted`,
    );
  }

  // Newlines are normalised because the marker is matched across one, and a checkout on Windows
  // writes files with the pair.
  const tokens = marked.lexer(
    fillGenerated(readFileSync(path, 'utf8').replace(/\r\n/g, '\n')),
  );
  const seen = new Set<string>();
  const headings: DocHeading[] = [];

  for (const token of tokens) {
    if (token.type !== 'heading') continue;

    const heading = token as HeadingWithId;
    heading.id = uniqueId(slugify(heading.text), seen);
    if (heading.depth >= 2) {
      headings.push({ depth: heading.depth, text: heading.text, id: heading.id });
    }
  }

  return { entry, html: marked.parser(tokens), headings };
}
