import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { Marked, type Tokens } from 'marked';

export interface DocEntry {
  /** The heading this page sits under in the contents. Groups appear in first-mention order. */
  group: string;
  /** The URL segment and the filename, without `.md`. Keeping them one value is the drift guard. */
  slug: string;
  title: string;
  summary: string;
}

export interface DocGroup {
  group: string;
  entries: DocEntry[];
}

export interface DocHeading {
  depth: number;
  text: string;
  id: string;
}

export interface DocPage {
  entry: DocEntry;
  html: string;
  /** Sections the reader can be sent to — `##` and below. The page's own `#` is its title. */
  headings: DocHeading[];
}

/** One field of a body or a query string, as the validator that guards it describes itself. */
export interface RequestFieldDoc {
  name: string;
  optional: boolean;
  conditional: boolean;
  nested: boolean;
  /** What the route answers when this field is wrong, in the validator’s own words. */
  rules: string[];
  /** The closed set an enumerated field accepts, empty when the field is not enumerated. */
  values: string[];
}

export interface EndpointRequestDoc {
  params: string[];
  query: RequestFieldDoc[];
  body: RequestFieldDoc[];
}

/** One key of the answer, as the type the handler declares spells it. */
export interface ResponseFieldDoc {
  name: string;
  type: string;
  optional: boolean;
  note: string;
}

/**
 * An object the answer reaches through.
 *
 * A field typed `user: AuthUser` says nothing to the reader who has to draw the row, so the keys one
 * name away travel with the answer that points at them.
 */
export interface ResponseTypeDoc {
  name: string;
  note: string;
  fields: ResponseFieldDoc[];
}

export interface EndpointResponseDoc {
  kind: 'json' | 'none' | 'stream';
  declared: string;
  note: string;
  fields: ResponseFieldDoc[];
  types: ResponseTypeDoc[];
}

/** One row of the table the API writes; see `apps/api/src/docs/endpoint-reference.ts`. */
export interface EndpointDoc {
  method: string;
  path: string;
  statusCode: number;
  access: { kind: 'public' | 'optional-session' | 'session'; roles: string[] };
  request: EndpointRequestDoc;
  response: EndpointResponseDoc;
  controller: string;
  handler: string;
}

export interface EndpointsFile {
  generatedBy: string;
  endpoints: EndpointDoc[];
}

/** One column, as the code names it and as the table names it. */
export interface ModelColumnDoc {
  name: string;
  column: string;
  type: string;
  optional: boolean;
}

/** A pointer a row holds: the field, the table it leads to, the columns carrying the key. */
export interface ModelRelationDoc {
  field: string;
  type: string;
  columns: string[];
  onDelete: string;
}

/** One row of the schema export; see `apps/api/src/docs/data-model.ts`. */
export interface ModelDoc {
  name: string;
  table: string;
  columns: ModelColumnDoc[];
  relations: ModelRelationDoc[];
  uniqueKeys: string[][];
  softDelete: boolean;
  tracksUpdates: boolean;
}

export interface DataModelFile {
  generatedBy: string;
  models: ModelDoc[];
}

const CONTENT_DIR = resolve(process.cwd(), 'content');

/**
 * The manifest is read rather than imported so that a page can be added by writing a file and a
 * line here, with no third place to remember.
 */
const ENTRIES = JSON.parse(readFileSync(resolve(CONTENT_DIR, 'docs.json'), 'utf8')) as DocEntry[];

/**
 * The route table and the shape of the data, both generated by the API package and committed as
 * files. Read once at module load so that a missing or corrupt export stops the build rather than
 * printing a page whose table is quietly shorter than the API.
 */
const ENDPOINTS = JSON.parse(
  readFileSync(resolve(CONTENT_DIR, 'endpoints.json'), 'utf8'),
) as EndpointsFile;

const DATA_MODEL = JSON.parse(
  readFileSync(resolve(CONTENT_DIR, 'data-model.json'), 'utf8'),
) as DataModelFile;

/**
 * The repository's own README, three folders up from this package's `content` directory.
 *
 * The phase record on the site is this file's table and nothing else. A second copy of a roadmap is
 * the classic way for documentation to disagree with itself, and the page has no reason to exist if
 * it is going to be typed out again.
 */
const README_PATH = resolve(CONTENT_DIR, '../../../README.md');

interface PhaseRow {
  phase: string;
  scope: string;
  status: string;
}

function readmePhases(): PhaseRow[] {
  const source = readFileSync(README_PATH, 'utf8').replace(/\r\n/g, '\n');

  return [...source.matchAll(/^\| (\d+)\s*\| (.+?)\s*\| (.+?)\s*\|$/gm)].map((match) => ({
    phase: match[1] ?? '',
    scope: match[2] ?? '',
    status: match[3] ?? '',
  }));
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

/**
 * Ids have to be stable across builds and unique within a page. A reader sent to `#the-api` should
 * land on the section they were promised even after a second heading with the same words is added
 * above it, so the collision is resolved by position rather than by a hash of the content.
 */
function uniqueId(base: string, seen: Set<string>): string {
  const root = base || 'section';
  let id = root;
  let taken = 2;

  while (seen.has(id)) {
    id = `${root}-${taken}`;
    taken += 1;
  }
  seen.add(id);
  return id;
}

type HeadingWithId = Tokens.Heading & { id?: string };

const marked = new Marked({ gfm: true });

marked.use({
  renderer: {
    heading(token) {
      const heading = token as HeadingWithId;
      const id = heading.id ?? slugify(heading.text);
      return `<h${heading.depth} id="${id}">${marked.parseInline(heading.text, { async: false })}</h${heading.depth}>`;
    },
  },
});

export function docSlugs(): string[] {
  return ENTRIES.map((entry) => entry.slug);
}

/**
 * Every path the export emits for the docs, and the only list an internal link on this site is
 * allowed to point at. The index is deliberately given the short path rather than also appearing
 * as `/docs/index`: two URLs for one page is two things that can drift, and one of them would be
 * a link nobody wrote on purpose.
 */
export function docRoutes(): string[] {
  return [
    '/docs',
    ...ENTRIES.filter((entry) => entry.slug !== 'index').map((entry) => `/docs/${entry.slug}`),
  ];
}

export function docGroups(): DocGroup[] {
  const order: string[] = [];
  const byGroup = new Map<string, DocEntry[]>();

  for (const entry of ENTRIES) {
    const existing = byGroup.get(entry.group);
    if (existing) {
      existing.push(entry);
    } else {
      byGroup.set(entry.group, [entry]);
      order.push(entry.group);
    }
  }

  return order.map((group) => ({ group, entries: byGroup.get(group) as DocEntry[] }));
}

/**
 * The one sentence a reader needs beside a path: not the decorator's word for it but who, in
 * practice, gets past the guard.
 */
function accessLabel(access: EndpointDoc['access']): string {
  if (access.kind === 'public') return 'anyone';
  if (access.kind === 'optional-session') return 'anyone, session read if offered';

  return access.roles.length > 0 ? access.roles.join(' or ') : 'any signed-in account';
}

function resourceOf(path: string): string {
  // `/api/v1/<resource>/…` — the segment a reader is scanning for once they know the URL.
  return path.split('/')[3] ?? '';
}

/**
 * One table per resource, because sixty routes in a single block is a page nobody can hold still
 * long enough to search. The groups come out in the order the export sorted them, which is by path,
 * so a reader who knows the URL does not have to know the module layout to find it.
 */
function endpointTables(): string {
  const groups: { resource: string; rows: EndpointDoc[] }[] = [];

  for (const endpoint of ENDPOINTS.endpoints) {
    const resource = resourceOf(endpoint.path);
    const last = groups[groups.length - 1];

    if (last?.resource === resource) last.rows.push(endpoint);
    else groups.push({ resource, rows: [endpoint] });
  }

  return groups
    .map((group) =>
      [
        `### ${group.resource}`,
        '',
        '| Method | Path | Who may call | Answers |',
        '| --- | --- | --- | --- |',
        ...group.rows.map(
          (row) =>
            `| \`${row.method}\` | \`${row.path}\` | ${accessLabel(row.access)} | ${row.statusCode} |`,
        ),
      ].join('\n'),
    )
    .join('\n\n');
}

/**
 * The heading a page writes when it explains one route on its own: the method, a space, and the
 * address the export gave it. Nothing else in the prose is allowed to look like this, and the
 * renderer treats a match as a promise that the route exists.
 */
const ENDPOINT_HEADING = /^(#{1,6}\s+)?(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS) (\/\S*)$/u;

/**
 * The anchor a reader is sent to for one route.
 *
 * `slugify` would fold `POST /api/v1/auth/login` into `post-apiv1authlogin`, which is neither
 * readable in a link nor what anybody would type. The version here keeps the words a caller is
 * already holding — the method and the path with its prefixes and colons off.
 */
function endpointHeadingId(method: string, path: string): string {
  const tail = path
    .replace(/^\/api\/v1/u, '')
    .replace(/:(\w+)/gu, (_match, name: string) => name.toLowerCase())
    .replace(/\W+/gu, '-');

  return `${method.toLowerCase()}-${tail.replace(/^-|-$/gu, '')}`;
}

function endpointOf(method: string, path: string): EndpointDoc {
  const found = ENDPOINTS.endpoints.find(
    (endpoint) => endpoint.method === method && endpoint.path === path,
  );

  if (!found) {
    throw new Error(
      `${method} ${path} is explained on a docs page but is not a route the API answers — ` +
        'run `bun run --filter @lms/api docs:export` and either fix the heading or the export',
    );
  }

  return found;
}

/** Text that came from code, made safe to put inside markup this page writes itself. */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * A sentence written above a type or a field, put on the page as its author meant it.
 *
 * The comments in `packages/shared` mark a type name with backticks because they are read in an
 * editor, where that is how a developer writes one; a page that printed the characters would show
 * somebody's markup instead of their sentence.
 */
function noteText(text: string): string {
  return escapeHtml(text).replace(/`([^`]+)`/gu, '<code>$1</code>');
}

/** The one line a field carries about how it behaves rather than what it looks like. */
function fieldFlag(field: RequestFieldDoc): string {
  if (field.optional) return 'may be left out';
  if (field.conditional) return 'only when another field asks for it';
  if (field.nested) return 'a nested object';

  return '';
}

/** What the route answers when a field is wrong — its own sentence, not a paraphrase of it. */
function fieldRules(field: RequestFieldDoc): string {
  // An enumerated field states its set twice otherwise, once as a sentence and once as the words a
  // caller may actually send. The chips are the more useful of the two.
  const rules = field.values.length > 0
    ? field.rules.filter((rule) => !rule.startsWith('one of:'))
    : field.rules;

  const parts = rules.map((rule) => escapeHtml(rule));

  if (field.values.length > 0) {
    parts.push(`one of ${field.values.map((value) => `<code>${escapeHtml(value)}</code>`).join(' ')}`);
  }

  return parts.join(' · ');
}

function requestFields(source: string, fields: RequestFieldDoc[]): string {
  if (fields.length === 0) return '';

  return [
    `<table class="endpoint-fields">`,
    `<caption>${source}</caption>`,
    '<thead><tr><th>Field</th><th>What the route accepts</th></tr></thead>',
    '<tbody>',
    ...fields.map((field) => {
      const flag = fieldFlag(field);

      return [
        '<tr>',
        `<td><code>${escapeHtml(field.name)}</code>${
          flag ? ` <span class="endpoint-flag">${flag}</span>` : ''
        }</td>`,
        `<td>${fieldRules(field) || '—'}</td>`,
        '</tr>',
      ].join('');
    }),
    '</tbody>',
    '</table>',
  ].join('');
}

/** One set of keys, whether they are the answer's own or an object the answer reaches through. */
function keyTable(caption: string, fields: ResponseFieldDoc[]): string {
  return [
    '<table class="endpoint-fields">',
    `<caption>${caption}</caption>`,
    '<thead><tr><th>Key</th><th>Type</th><th>What it holds</th></tr></thead>',
    '<tbody>',
    ...fields.map(
      (field) =>
        `<tr><td><code>${escapeHtml(field.name)}</code>${field.optional ? '?' : ''}</td>` +
        `<td><code>${noteText(field.type)}</code></td>` +
        `<td>${field.note === '' ? '—' : noteText(field.note)}</td></tr>`,
    ),
    '</tbody>',
    '</table>',
  ].join('');
}

/** The answer half: the keys a body holds, then every object those keys lead to. */
function responseFields(response: EndpointResponseDoc): string {
  if (response.kind === 'none') {
    return '<p class="endpoint-empty">A successful call answers with the status and no body.</p>';
  }

  if (response.kind === 'stream') {
    return '<p class="endpoint-empty">The bytes of the file itself, not JSON. The route takes the response over, so it answers <code>206</code> to a range the player asks for and <code>416</code> to one it cannot meet.</p>';
  }

  if (response.fields.length === 0) {
    return `<p class="endpoint-empty">Answers with a plain <code>${escapeHtml(response.declared)}</code> rather than an object of named keys.</p>`;
  }

  const own = keyTable(`Answers <code>${escapeHtml(response.declared)}</code>`, response.fields);
  const note = response.note === '' ? '' : `<p class="endpoint-note">${noteText(response.note)}</p>`;

  // The nested keys go under a fold rather than in the open: a course page answers with five objects
  // deep, and a reader who came for one field should still be able to see the whole card at once.
  const nested = response.types.map(
    (type) =>
      `<details class="endpoint-nested"><summary><code>${escapeHtml(type.name)}</code>` +
      `<span>${type.fields.length} keys</span></summary>` +
      (type.note === '' ? '' : `<p class="endpoint-note">${noteText(type.note)}</p>`) +
      keyTable('Keys', type.fields) +
      '</details>',
  );

  return [own, note, ...nested].join('');
}

/**
 * Everything a page can honestly say about one route without a human writing it: who gets past the
 * guard, what the caller sends, what the route gives back, and which class serves it.
 *
 * This is the half that would otherwise be typed out per route and go stale per route. The prose a
 * writer puts around it is the half only a person can supply.
 */
function endpointCard(method: string, path: string): string {
  const endpoint = endpointOf(method, path);
  const { request, response } = endpoint;

  return [
    '<div class="endpoint-card">',
    '<dl class="endpoint-facts">',
    `<div><dt>Who may call</dt><dd>${escapeHtml(accessLabel(endpoint.access))}</dd></div>`,
    `<div><dt>Success</dt><dd><code>${endpoint.statusCode}</code></dd></div>`,
    ...(request.params.length > 0
      ? [
          `<div><dt>Address</dt><dd>${request.params
            .map((param) => `<code>${escapeHtml(param)}</code>`)
            .join(' ')}</dd></div>`,
        ]
      : []),
    '</dl>',
    ...(request.body.length > 0 || request.query.length > 0
      ? [requestFields('Body', request.body), requestFields('Query', request.query)]
      : ['<p class="endpoint-empty">Sends no body and no query string.</p>']),
    responseFields(response),
    `<p class="endpoint-source">Served by <code>${escapeHtml(endpoint.controller)}.${escapeHtml(
      endpoint.handler,
    )}</code></p>`,
    '</div>',
  ].join('');
}

/**
 * The authored headings that name a route, with the generated contract hung under each one.
 *
 * A fenced block is skipped rather than matched: an example of somebody else's API documentation in
 * a page would otherwise be read as a promise about a route this API does not answer.
 */
export function explainEndpoints(markdown: string): string {
  const lines = markdown.split('\n');
  const out: string[] = [];
  let inFence = false;

  for (const line of lines) {
    if (line.trimStart().startsWith('```')) {
      inFence = !inFence;
      out.push(line);
      continue;
    }

    const heading = inFence ? undefined : ENDPOINT_HEADING.exec(line.trim());

    if (!heading) {
      out.push(line);
      continue;
    }

    out.push(line, '', endpointCard(heading[2] ?? '', heading[3] ?? ''), '');
  }

  return out.join('\n');
}

/**
 * The record as the repository keeps it: every phase, what it was for, and whether it shipped.
 *
 * The scope text arrives with the emphasis markers the README writes its statuses with, and marked
 * turns those into bold on this page too — so the table is passed through rather than reworded,
 * which is the whole point of reading it from one file.
 */
function phaseTable(): string {
  return [
    '| Phase | What it was for | Status |',
    '| --- | --- | --- |',
    ...readmePhases().map((row) => `| ${row.phase} | ${row.scope} | ${row.status} |`),
  ].join('\n');
}

/**
 * The fence a page writes to ask for a generated block. The body is allowed to be blank because a
 * formatter passing over an empty code block puts a line inside it, and a marker that only matches
 * the exact bytes it was written with breaks on a reflow rather than on a real mistake.
 */
const ENDPOINT_MARKER = /^```endpoints\n[ \t\n]*```$/m;
const DATA_MODEL_MARKER = /^```data-model\n[ \t\n]*```$/m;
const PHASES_MARKER = /^```phases\n[ \t\n]*```$/m;

function tableOf(modelName: string): string {
  return DATA_MODEL.models.find((model) => model.name === modelName)?.table ?? modelName;
}

/** `DateTime?` and `String[]` — Prisma's own notation, which is what a reader edits. */
function typeCell(column: ModelColumnDoc): string {
  return `${column.type}${column.optional ? '?' : ''}`;
}

function fieldList(names: string[]): string {
  return names.map((name) => `\`${name}\``).join(' + ');
}

/**
 * The physical names behind a set of fields, because a pointer and a unique key are both facts about
 * the table rather than about the code — and the column list above each one already shows the pair.
 */
function columnsOf(model: ModelDoc, fields: string[]): string[] {
  return fields.map(
    (field) => model.columns.find((column) => column.name === field)?.column ?? field,
  );
}

/** The two conventions, or their absence, in the fewest words that stay true for either case. */
function conventionNote(model: ModelDoc): string {
  const parts: string[] = [];

  parts.push(model.softDelete ? 'retireable' : 'no retirement flag');
  if (!model.tracksUpdates) parts.push('no update stamp');

  return parts.join(', ');
}

/**
 * One section per table: its columns under both names, the rows it points at, the rows that point
 * at it, and the keys that cannot repeat.
 *
 * The pointers are read in both directions because the schema writes each pair once, on the side
 * that holds the key. A reader of `users` therefore has to be shown the far halves of those pairs
 * or the busiest table on the page looks like it does nothing.
 */
function modelSections(): string {
  return DATA_MODEL.models
    .map((model) => {
      const heldBy = DATA_MODEL.models
        .flatMap((other) => other.relations.map((relation) => ({ other, relation })))
        .filter(({ relation }) => relation.type === model.name)
        .map(
          ({ other, relation }) =>
            `- \`${other.table}\` holds it as \`${relation.field}\`, from ${fieldList(
              columnsOf(other, relation.columns),
            )}`,
        );

      return [
        `### ${model.name}`,
        '',
        `Table \`${model.table}\` — ${model.columns.length} columns, ${conventionNote(model)}.`,
        '',
        '| Field | Column | Type |',
        '| --- | --- | --- |',
        ...model.columns.map(
          (column) => `| \`${column.name}\` | \`${column.column}\` | \`${typeCell(column)}\` |`,
        ),
        '',
        ...(model.relations.length > 0
          ? [
              '**Points at**',
              '',
              ...model.relations.map(
                (relation) =>
                  `- \`${relation.field}\` → \`${tableOf(relation.type)}\`, from ${fieldList(
                    columnsOf(model, relation.columns),
                  )}, \`${relation.onDelete}\``,
              ),
              '',
            ]
          : []),
        ...(heldBy.length > 0 ? ['**Held by**', '', ...heldBy, ''] : []),
        ...(model.uniqueKeys.length > 0
          ? [
              '**Cannot repeat**',
              '',
              ...model.uniqueKeys.map((key) => `- ${fieldList(columnsOf(model, key))}`),
            ]
          : []),
      ]
        .join('\n')
        .trimEnd();
    })
    .join('\n\n');
}

/**
 * A fence rather than a template tag, so the marker survives as something a markdown reader can
 * see: an unfilled ```endpoints block prints its own name on the page, which is the failure the
 * "no marker unfilled" test is watching for.
 */
function fillGenerated(markdown: string): string {
  return markdown
    .replace(ENDPOINT_MARKER, endpointTables())
    .replace(DATA_MODEL_MARKER, modelSections())
    .replace(PHASES_MARKER, phaseTable());
}

export function readDoc(slug: string): DocPage {
  const entry = ENTRIES.find((candidate) => candidate.slug === slug);

  if (!entry) {
    throw new Error(`No docs page "${slug}": content/docs.json does not list it`);
  }

  const path = resolve(CONTENT_DIR, `${slug}.md`);
  if (!existsSync(path)) {
    throw new Error(
      `content/docs.json lists "${slug}" but content/${slug}.md is not there — the manifest and the folder have drifted`,
    );
  }

  // Newlines are normalised because the marker is matched across one, and a checkout on Windows
  // writes files with the pair.
  const tokens = marked.lexer(
    explainEndpoints(fillGenerated(readFileSync(path, 'utf8').replace(/\r\n/g, '\n'))),
  );
  const seen = new Set<string>();
  const headings: DocHeading[] = [];

  for (const token of tokens) {
    if (token.type !== 'heading') continue;

    const heading = token as HeadingWithId;
    const route = ENDPOINT_HEADING.exec(heading.text);

    heading.id = uniqueId(
      route ? endpointHeadingId(route[2] ?? '', route[3] ?? '') : slugify(heading.text),
      seen,
    );
    if (heading.depth >= 2) {
      headings.push({ depth: heading.depth, text: heading.text, id: heading.id });
    }
  }

  return { entry, html: marked.parser(tokens), headings };
}
